name: Checks

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  template-packages-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: set up weaver
      uses: open-telemetry/weaver/.github/actions/setup-weaver@adcf6fda79c3df1cb537669442aef753b7019777 # v0.24.2
    - name: verify template packages
      run: ./buildscripts/test_weaver_templates.sh
  policy-packages-check:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: set up weaver
      uses: open-telemetry/weaver/.github/actions/setup-weaver@adcf6fda79c3df1cb537669442aef753b7019777 # v0.24.2
    - name: verify policy packages
      run: ./buildscripts/test_weaver_policies.sh
